name: Humble Source Build
on:
  workflow_dispatch:
    branches:
      - humble
  push:
    branches:
      - humble
#  schedule:
#    # Run every morning to detect flakiness and broken dependencies
#    - cron: '03 1 * * *'


jobs:
  source:
    uses: ./.github/workflows/reusable-ros-tooling-source-build.yml
    with:
      ros_distro: humble
      ref: humble
      ros2_repo_branch: humble
