name: Rolling Source Build
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
#  schedule:
#    # Run every morning to detect flakiness and broken dependencies
#    - cron: '03 1 * * *'


jobs:
  source:
    uses: ./.github/workflows/reusable-ros-tooling-source-build.yml
    with:
      ros_distro: rolling
      ref: master
      ros2_repo_branch: rolling
